export { default as HomePage } from './HomePage.jsx'
export { default as LoginPage } from './LoginPage.jsx'
export { default as RegisterPage } from './RegisterPage.jsx'
export { default as RoomDetailsPage } from './RoomDetailsPage.jsx'
export { default as DashBoardPage } from './DashBoardPage.jsx'